---
title: "Intro and Methods"
author: "Clara Dawson"
date: "2023-11-16"
output: html_document
---

```{r}
#Introduction 

#As the rapid growth of urbanization surges across the globe, the expansion of road infrastructure continues to increase. Due to this increase, the ecological effect that road traffic has on wildlife populations is a growing concern for many countries (Kučas et al. 2023). This expanding linear network poses a major threat to biodiversity, as habitat loss and fragmentation have resulted from roadways extending into what was once pure, pristine wildlife habitat (Ng et al. 2003). Landscape connectivity is incredibly important for supporting biological processes, such as animal movement and gene flow (Veals et al. 2022). Road systems that have impeded this connectivity have had negative impacts on wildlife, such as displacement from essential habitat, restriction of physical movements, and exposure to mortality by vehicle collisions (Kang et al. 2016). Wildlife-vehicle collisions occur where heavily travelled roads intersect with animal movement corridors (Kučas et al. 2023). Vehicular collisions threaten the lives of both humans and animals, while also resulting in significant damage to property. In the United States alone, collisions involving white-tailed deer result in approximately 200 human fatalities, 30 thousand injuries, and more than $1 billion in property damage annually (Fudge et al. 2007). It is suggested that wildlife species with the highest collision risk are large mammals, such as large carnivores and ungulates, because they regularly move over great distances (Ng et al. 2003). Large mammalian carnivores are particularly sensitive to habitat fragmentation, as they tend to have traits that make them more vulnerable, such as large body size, large area requirements and slow population growth rates (Crooks et al. 2011). There have been numerous studies on causes of roadkill that suggest that there is a plethora of factors that can influence collision probability. Some studies have reported that traffic volume was highly correlated with roadkill risk, whereas others have found road topography to be an important factor in explaining roadkill rates (Kang et al. 2016). However, because different species exhibit different dispersal behaviors, explanatory variables for collision risk may differ significantly between species (Kang et al. 2016; Girardet et al. 2015). The wildlife-vehicle collision dataset provided by the New Hampshire Department of Transportation spans over five years (2015-2019) and provides the opportunity to examine species-specific roadkill data, as well as road features and weather data that may play a significant role in collision probability. This dataset was compiled from police reports across the state of New Hampshire. Out of the five years documented, only in the year 2017 did the reports include data on the specific animal involved in the collision (limited to moose, deer, black bear, turkey). In this study, I will use the dataset collected by NH DOT to observe temporal trends and additional relationships of independent factors with wildlife-vehicle collisions across the state. 

```


```{r}

#Methods

#Data cleaning and organization
#The dataset used for this analysis came from police reports of wildlife-vehicle collisions that occurred between the years 2015 and 2019. Data that was recorded during these reports included 127 columns of key information, such as date and time the collision occurred, day of the week, town, weather condition, light condition, and posted speed. The data from these police reports was compiled into a spreadsheet, which was then given to the NH Department of Transportation (DOT). Using this raw data provided by the New Hampshire DOT, a .csv file was created and imported into R studio using the “read.csv” command. The data was cleaned using the lubridate package, which was utilized to condense the date and time data into a standard format. The first step was to convert the “CRASHTIME” column from military time into standard time using the sprintf() function. This column contained times that ranged from having one to four digits depending on the time of day (1300 was one o’clock in the afternoon whereas 23 was understood as twenty-three minutes after midnight), so this function was used to convert all times to read as either AM or PM within the dataset. The next step was to convert the dataset into a standard date and time to a universally accepted format using the POSIXct() function. From this, a new column “tp” was made available with all the standardized crash times and dates compiled together. To make plotting simpler, new columns were made for hour, month, year, and day of the week. The tidyverse package was loaded into the R script in preparation for plotting various trends and relationships.

#Temporal patterns: collision relationships based on hour, day of week, and month.
#First, to determine if there were significant differences in wildlife-vehicle collisions (WVCs) based on the hour of the day, I created histograms using the hist() function for the average number of crashes per hour for the months of December and June. These months were chosen since they have the shortest and longest hours of daylight, respectively. In order to evaluate the relationship between the hour of day and the occurrence of WVCs, I ran a One-Way Anova between the two factors. An ANOVA was used to test the influence that the hour of the day had on the magnitude of WVCS and whether the  relationship between the two was statiscally significant. The ANOVA test will provide essential information used to determine significance between the two variables of interest, such as the p-value and F Value.
#Using ggplot2, a histogram was created using geom_histogram to assess the relationship between the hour of individual collisions and the month. With the geom_histogram function, I changed the bins to equal 24 so the data would read consistently with the hours of the day. I facet-wrapped the function to be associated with month_name and edited ylab and xlab to be “Count” and “Hour of the Day”, respectively. This procedure was repeated to assess the relationship between the hour of individual collisions and the year. One-way ANOVAs were conducted to assess the influence of both month and year on the hour that wildlife-vehicle collisions take place.
#Using an “ifelse” statement, a new column was created to measure weekend vs weekday. In the creation of a new object “wday_2”, the condition statement indicated that if true, the data would read “Weekend” and if false it would read “Weekday”.  Using ggplot2, a histogram was created to assess the relationship between the hour of the day and the overall count of collisions with weekend vs. weekday. 


#Evaluating species-specific collision data
#To evaluate patterns between months of the year and collision data, I used ggplot2 to create a bar graph using geom_bar, where x is equal to month_name and y is equal to CRASHTYPE. To visualize the differences between species-specific data, I set the fill to equal “CRASHTYPE” in the ggplot2 function so that each species is a different color.
#Using the mutate function, I created a new column named "Species" where the six CRASHTYPE variables were renamed and condensed into five variables. This allowed the "Animal" variable and "Animal(Other)" variable to be named the same. The other variables were renamed to where the (Other) part of the name was dropped (Moose(Other) was renamed to be Moose). 
#I then created a new object called “speciesdata” where I used the filter function to restrict the year to equal 2017 and for "Species" to not be equal to either “Animal” or “Animal(Other)”. This allowed the object to only contain collision data for the four identified species (moose, deer, black bear, turkey).  


#Relationships between collision data and independent factors
#To determine if there were any factors that played a significant role in the probability of a wildlife-vehicle collision, several bar graphs were created in ggplot2 using geom_bar to show the relationship between collision abundance and light condition, weather condition and road alignment. A bar graph was also created to show which counties had the highest abundance of collisions over the course of the five-year study period.




```



```{r}
```

