---
title: "Result and Analysis"
author: "Clara Dawson"
date: "2023-11-20"
output: html_document
---

    ```{r setup, include=FALSE}
    
library(lubridate)
library(tidyverse)
library(dplyr)
    
```



```{r data}

d <- read.csv("allroadkilldata.csv")
names(d)

```



```{r data cleaning}

#Standardized time
# d$tp <- as.POSIXct(d$t,format = "%m/%d/%Y %H%M")
# sum(is.na(d$tp))
# d$tp
# d$t[895]
# d$t[981]
# d$t[949:950]
# str(d)
# d$CRASHTIME <- hm(d$CRASHTIME)
# print(d$CRASHTIME)

# Convert military time numbers to standard time 
d$CRASHTIME <- sprintf("%02d:%02d %s",
                          d$CRASHTIME %/% 100, # Extract the hour
                          d$CRASHTIME %% 100,  # Extract the minutes
                          ifelse(d$CRASHTIME < 1200, "AM", "PM")  # Determine AM or PM
)

print(d$CRASHTIME)
d$t <- paste(d$CRASHDATE,d$CRASHTIME)
d$t

d$tp <- as.POSIXct(d$t,format = "%m/%d/%Y %H:%M")
d$tp
sum(is.na(d$tp))

hour(d$tp)
minute(d$tp)

# create hour column
d$hour <- hour(d$tp)

# create month column
d$month <- month(d$tp)
d$month_name <- month(d$tp, label = TRUE)

# create year column
d$year <- year(d$tp)


#create new column with only 5 species-specific items- clean names
d <- d %>%
  mutate(Species = case_when(
    CRASHTYPE %in% c("Animal", "Animal(Other)") ~ "Animal",
    CRASHTYPE %in% c("Black Bear(Animal)") ~ "Black Bear", 
    CRASHTYPE %in% c("Deer(Animal)") ~ "Deer", 
    CRASHTYPE %in% c("Moose(Animal)") ~ "Moose", 
    CRASHTYPE %in% c("Turkey(Animal)") ~ "Turkey", 
  ))

#create new object with just four species (clean version)
speciesdata <- d %>%
  filter(year==2017) %>%
  filter(Species != "Animal")


```

```{r crashes with respect to hour}

# histogram of crashes by hour in dec
hist(hour(d$tp)[month(d$tp)==12]) 

#Frequency of crashes per hour in the month of December over the 2015-2019 period. During the month of December, the number of recorded wildlife-vehicle collisions occurred more frequently late in the afternoon, peaking around 4:00-5:00pm. Fewer collisions occurred during the middle of the day, with the lowest numbers around 12:00pm.


# histogram of crashes by hour in june
hist(hour(d$tp)[month(d$tp)==6])

#Frequency of crashes per hour in the month of June over the 2015-2019 period. During the month of June, the number of recorded wildlife-vehicle collisions was highest in the evening. The peak number of collisions occurred around 9:00-10:00pm, while the lowest number of collisions occurred around midnight. Overall, the number of collisions stayed relatively consistent throughout the day from 4:00am to 6:00pm.

# histogram of hour of crash (facet by month)
ggplot(d, aes(x = hour)) +
  geom_histogram(bins = 24) +
  facet_wrap(~ month_name) +
  theme_bw() +
  ylab("Count") +
  xlab("Hour of the day")

#run an anova for month vs hour
aov_hour2 <- aov(month~hour, data = d)
summary(aov_hour2)

#Frequency of crashes by the hour for each individual month during 2015-2019. During the month of November, the magnitude of vehicle collisions was significantly higher than any other month, with a large spike of collisions occurring later in the afternoon around 4:00-5:00pm.  An Anova was run for hour vs month, and the p-value resulting from this analysis is 0.0134. This indicated that there was a significant relationship between the hour of the day and the month of the year for the collision occurrences. 


#histograms of hour of crash (facet by year)
ggplot(d, aes(x = hour)) +
  geom_histogram(bins = 24) +
  facet_wrap(~ year) +
  theme_bw() +
  ylab("Count") +
  xlab("Hour of the day")

#run an anova for year vs hour
aov_year2 <- aov(hour~year, data = d)
summary(aov_year2)

#Average of crashes by hour for the years 2015-2019. Across the five years of data collection, the trend of collisions by hour stayed relatively consistent. An Anova was run for hour vs year, and the p-value was 0.0527, which indicated that there wasn’t a significant relationship between the two variables.

# create day of the week column
d$wday <- wday(d$tp, label = TRUE)

# get new column that is weekday vs. weekend
d$wday_2 <- ifelse(d$wday %in% c("Sat","Sun"), # condition statement
                   "Weekend", # value if condition statement is true
                   "Weekday") # value if condition statement is false

# show what is happening above
data.frame(d$wday,d$wday %in% c("Sat","Sun"))

# crashes by hour faceted by weekend vs weekday
ggplot(d, aes(x = hour)) +
  geom_histogram(bins = 24) +
  facet_wrap(~ wday_2) +
  theme_bw() +
  ylab("Count") +
  xlab("Hour of the day")

#Average crashes by hour on weekdays vs weekends. Over the course of the five year-study period, the magnitude of collisions occurring during the weekday was significantly higher than that on the weekend. The hourly trend for when collisions occurred overall was consistently highest later in the day around 4:00-5:00pm. 

```

```{r Collision patterns by species}

#plot species specific crash data for each month (without general animals)
ggplot(data = speciesdata, aes(x = month_name, y = Species, fill= Species)) + 
  geom_bar(stat = "identity") +
  ylab("Count") +
  xlab("Months")

#run an anova for month vs species
aov_speciesmonth3 <- aov(month~Species, data = speciesdata)
summary(aov_speciesmonth3)

#run a TUKEY test for aov_speciesmonth3
tukeyspecies_month <- TukeyHSD(aov_speciesmonth3)
print(tukeyspecies_month)

#species specific collisions per month during 2017. During the year 2017, moose collisions were the most common type of collision to occur in New Hampshire. Out of the months that had species-specific data recorded, June had the highest number of collisions occur. September and March were the months with the fewest recorded species-specific vehicle collisions. An Anova was run comparing the month with the species-specific vehicle collisions. The p-value was 1.86e-7 and the F-value was 11.95. As these values are incredibly small and large, respectively, the ANOVA analysis suggests that there is significant relationship between the month of the year and species-specific collisions in the year 2017. Using this ANOVA model, I ran tukey test to help identify any significant differences between groups of species included in the data.

#plot species specific crash data for each month 
ggplot(data = d, aes(x = month_name, y = Species, fill= Species)) + 
  geom_bar(stat = "identity") +
  ylab("Count") +
  xlab("Months")

#run an anova for month vs general roadkill
aov_speciesmonth2 <- aov(month~Species, data = d)
summary(aov_speciesmonth2)

#species specific collisions per month during 2015-2019. The magnitude of wildlife-vehicle collisions was highest in the month of November, followed by June. The number of collisions was lowest during the late winter/early spring months (Feb-April) as well as in August and September. An Anova was run comparing the statistical significance of the month and its effect on wildlife vehicle collisions. With the p-value being <2e-16, the analysis suggested that there was a significant relationship between the two variables, as well as provided strong evidence to reject the null hypothesis. The F-value, 34.97, was high and reinforced the evidence against the null hypothesis. 


#plot the relationship between general roadkill and county with axis labels
ggplot(data = d, aes(x = hour, y = COUNTY, fill = Species)) +
  geom_bar(stat = "identity") +
  ylab("County") +
  xlab("Hour of the day")

#run an anova for hour vs county (general roadkill)
aov_county <- aov(hour~COUNTY, data = d)
summary(aov_county)

#species specific collisions per county during 2015-2019. Across the five-year period, the county of Hillsborough had the highest number of wildlife-vehicle collisions occur, while Coos and Sullivan counties had the lowest number of collisions. An Anova was run to analyze the relationship between county and hour of collisions. The p-value was 0.108, which did not provide strong evidence to indicate that there was a significant difference between the two variables. The F-value was also relatively small (1.604), further supporting this idea.


#plot the relationship between species specific collisions and county with axis labels
ggplot(data = speciesdata, aes(x = hour, y = COUNTY, fill= Species)) +
  geom_bar(stat = "identity") +
  ylab("County") +
  xlab("Collisions")

#run an anova for hour vs county (species-specifc data)
aov_county2 <- aov(hour~COUNTY, data = speciesdata)
summary(aov_county2)

#species specific collisions per county during 2017 (Jan-Sept). In the year 2017, Merrimack County had highest number of moose collisions, followed by Grafton County. Merrimack had the highest number of species-specific collisions overall, with moose and deer dominating out of all four species. Carroll county had the lowest number of species-specific collisions in 2017. An Anova was run, and the analysis presented the p-value as 0.000798 and the F-value as 3.266. From this analysis, it is suggested that the county had a statistical significance on collisions occurrences. 


```

```{r Collision patterns with respect to independent variables}

#plot the relationship between collisions and light condition 
ggplot(data = d, aes(x = hour, y = LIGHTCONDI)) +
  geom_bar(stat = "identity") +
  ylab("Light Condition") +
  xlab("Collision")

#run an anova for hour vs light condition
aov_light <- aov(hour~LIGHTCONDI, data = d)
summary(aov_light)

#collisions in relation to light condition during 2015-2019. Over all five years, most wildlife-vehicle collisions occurred when it was dark and there was no streetlight. An Anova analysis indicated that this relationship was significant, as the p-value was <2e-16 and F-value was 143.5, which worked together to enforce the idea that the null hypothesis can be rejected.


#plot the relationship between collisions and road alignment 
ggplot(data = d, aes(x = hour, y = ROADALIGNM)) +
  geom_bar(stat = "identity") +
  ylab("Road Alignment") +
  xlab("Collision")

#run an anova for hour vs road alignment
aov_road <- aov(hour~ROADALIGNM, data = d)
summary(aov_road)

#collisions in relation to road alignment during 2015-2019. The largest amount of vehicle collisions that occurred on roads were identified to be straight and level. After running an Anova analysis, it was indicated that there was not enough strong evidence to suggest that there was a significant relationship between road alignment and vehicle collisions. The p-value was 0.668 and the F-value was 0.773.  


#plot the relationship between collisions and weather condition 
ggplot(data = d, aes(x = hour, y = WEATHERCON)) +
  geom_bar(stat = "identity") +
  ylab("Weather Condition") +
  xlab("Collision")

#run an anova for hour vs weather condition
aov_weather <- aov(hour~WEATHERCON, data = d)
summary(aov_weather)

#collisions in relation to weather condition during 2015-2019. Most wildlife vehicle collisions across the five-year period occurred when the weather was clear. After running an Anova analysis, it is suggested that there were significant differences between the two variables, as the p-value was 0.0031. This value, alongside the F-value of 2.408, supported the rejection of the null hypothesis. 








```

